import { NextRequest, NextResponse } from 'next/server';
import NodeID3 from 'node-id3';

export async function GET(request: NextRequest) {
  const url = request.nextUrl.searchParams.get('url');
  const title = request.nextUrl.searchParams.get('title') || 'Untitled';
  const author = request.nextUrl.searchParams.get('author') || 'anoncast';
  const imageUrl = request.nextUrl.searchParams.get('image') || '';

  if (!url) {
    return NextResponse.json({ error: 'Missing url parameter' }, { status: 400 });
  }

  // Convert proxied /api/audio/ URLs back to direct R2 URLs for server-side fetch
  let fetchUrl = url;
  if (url.startsWith('/api/audio/')) {
    const filename = url.replace('/api/audio/', '');
    fetchUrl = `https://pub-9c1086c73aa54425928d7ac6861030dd.r2.dev/${filename}`;
  }

  try {
    // Fetch the MP3 from R2
    const audioResponse = await fetch(fetchUrl);
    if (!audioResponse.ok) {
      return NextResponse.json({ error: 'Failed to fetch audio' }, { status: 502 });
    }
    const audioBuffer = Buffer.from(await audioResponse.arrayBuffer());

    // Build ID3 tags
    const tags: NodeID3.Tags = {
      title,
      artist: author,
      album: 'anoncast',
      comment: { language: 'eng', text: 'Generated by anoncast.net' },
    };

    // Embed cover image if available
    if (imageUrl) {
      try {
        const imgResponse = await fetch(imageUrl);
        if (imgResponse.ok) {
          const imgBuffer = Buffer.from(await imgResponse.arrayBuffer());
          const contentType = imgResponse.headers.get('content-type') || 'image/jpeg';
          const mime = contentType.startsWith('image/png') ? 'image/png' : 'image/jpeg';
          tags.image = {
            mime,
            type: { id: 3, name: 'front cover' },
            description: 'Cover',
            imageBuffer: imgBuffer,
          };
        }
      } catch {
        // Skip image embedding if fetch fails
      }
    }

    // Write ID3 tags to the audio buffer
    const taggedBuffer = NodeID3.write(tags, audioBuffer);
    if (!taggedBuffer || taggedBuffer instanceof Error) {
      // If tagging fails, return the original audio
      return new Response(audioBuffer, {
        headers: {
          'Content-Type': 'audio/mpeg',
          'Content-Disposition': `attachment; filename="${encodeFileName(title)}.mp3"`,
        },
      });
    }

    return new Response(new Uint8Array(taggedBuffer), {
      headers: {
        'Content-Type': 'audio/mpeg',
        'Content-Disposition': `attachment; filename="${encodeFileName(title)}.mp3"`,
      },
    });
  } catch (error) {
    console.error('Download with tags failed:', error);
    return NextResponse.json(
      { error: error instanceof Error ? error.message : 'Download failed' },
      { status: 500 }
    );
  }
}

function encodeFileName(title: string): string {
  return title.replace(/[^a-z0-9\s-]/gi, '').replace(/\s+/g, '_').toLowerCase() || 'podcast';
}
