#!/usr/bin/env node
/**
 * Fetch an episode from Supabase by ID and generate an MP4 video
 * with the cover image and audio.
 *
 * Usage:
 *   node scripts/supabase-to-mp4.js <episode-id> [output.mp4]
 *
 * Requires: ffmpeg installed, .env.local with SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY
 */

const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

// Load .env.local
const envPath = path.resolve(__dirname, '..', '.env.local');
if (fs.existsSync(envPath)) {
  const lines = fs.readFileSync(envPath, 'utf-8').split('\n');
  for (const line of lines) {
    const match = line.match(/^([^#=]+)=(.*)$/);
    if (match) process.env[match[1].trim()] = match[2].trim();
  }
}

const SUPABASE_URL = process.env.SUPABASE_URL;
const SUPABASE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!SUPABASE_URL || !SUPABASE_KEY) {
  console.error('Missing SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY in .env.local');
  process.exit(1);
}

async function fetchEpisode(episodeId) {
  const url = `${SUPABASE_URL}/rest/v1/episodes?id=eq.${episodeId}&select=*`;
  const res = await fetch(url, {
    headers: {
      apikey: SUPABASE_KEY,
      Authorization: `Bearer ${SUPABASE_KEY}`,
    },
  });
  if (!res.ok) {
    throw new Error(`Supabase fetch failed: ${res.status} ${await res.text()}`);
  }
  const rows = await res.json();
  if (rows.length === 0) {
    throw new Error(`No episode found with id: ${episodeId}`);
  }
  return rows[0];
}

async function downloadFile(url, destPath) {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Failed to download ${url}: ${res.status}`);
  const buf = Buffer.from(await res.arrayBuffer());
  fs.writeFileSync(destPath, buf);
  return destPath;
}

async function main() {
  const episodeId = process.argv[2];
  if (!episodeId) {
    console.error('Usage: node scripts/supabase-to-mp4.js <episode-id> [output.mp4]');
    process.exit(1);
  }

  console.log(`Fetching episode ${episodeId} from Supabase...`);
  const episode = await fetchEpisode(episodeId);

  console.log(`  Title: ${episode.title}`);
  console.log(`  Audio: ${episode.audio_url}`);
  console.log(`  Image: ${episode.image_url || '(none)'}`);

  const tmpDir = path.join(__dirname, '.tmp');
  if (!fs.existsSync(tmpDir)) fs.mkdirSync(tmpDir);

  // Download audio
  const mp3Path = path.join(tmpDir, 'audio.mp3');
  console.log('Downloading audio...');
  await downloadFile(episode.audio_url, mp3Path);

  // Download image (if available)
  let imagePath = null;
  if (episode.image_url) {
    const ext = episode.image_url.match(/\.(png|jpg|jpeg|webp)$/i)?.[1] || 'jpg';
    imagePath = path.join(tmpDir, `cover.${ext}`);
    console.log('Downloading cover image...');
    await downloadFile(episode.image_url, imagePath);
  }

  // Determine output path
  const safeName = (episode.title || 'episode')
    .replace(/[^a-z0-9\s-]/gi, '')
    .replace(/\s+/g, '_')
    .toLowerCase();
  const outputPath = process.argv[3]
    ? path.resolve(process.argv[3])
    : path.resolve(`./${safeName}.mp4`);

  // Escape metadata for shell safety
  const escMeta = (s) => (s || '').replace(/'/g, "'\\''");
  const metaTitle = escMeta(episode.title);
  const metaArtist = escMeta(episode.voice_id || 'anoncast');

  // Build ffmpeg command
  // -vf pad adds 1px if dimensions aren't divisible by 2 (libx264 requirement)
  console.log('Converting to MP4...');
  let ffmpegCmd;
  if (imagePath) {
    ffmpegCmd = `ffmpeg -y -loop 1 -i "${imagePath}" -i "${mp3Path}" -vf "pad=ceil(iw/2)*2:ceil(ih/2)*2" -c:v libx264 -tune stillimage -c:a aac -b:a 192k -shortest -pix_fmt yuv420p -metadata title='${metaTitle}' -metadata artist='${metaArtist}' -metadata comment='Generated by anoncast.net' "${outputPath}"`;
  } else {
    ffmpegCmd = `ffmpeg -y -f lavfi -i color=c=black:s=1280x720:r=25 -i "${mp3Path}" -c:v libx264 -tune stillimage -c:a aac -b:a 192k -shortest -pix_fmt yuv420p -metadata title='${metaTitle}' -metadata artist='${metaArtist}' -metadata comment='Generated by anoncast.net' "${outputPath}"`;
  }

  execSync(ffmpegCmd, { stdio: 'inherit' });

  // Cleanup
  fs.rmSync(tmpDir, { recursive: true, force: true });

  console.log(`\nDone! MP4 saved to: ${outputPath}`);
}

main().catch(err => {
  console.error('Error:', err.message);
  process.exit(1);
});
